import Head from "next/head";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const handleClick = () => {
    router.push("./Home");
  };
  return (
    <>
      <Head>
        <title>E-library</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex flex-col gap-6 justify-center items-center align-middle mt-72 mx-12">
          <h1 className="text-7xl text-rose-600 font-bold">E-library</h1>
          <p className="text-2xl text-fuchsia-600 font-semibold">
            You favourite books are at your fingertip now
          </p>

          <button
            onClick={handleClick}
            type="button"
            class="text-white bg-gradient-to-br from-pink-500 to-orange-400 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2"
          >
            Get Started
          </button>
        </div>
      </main>
    </>
  );
}
